language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - pypy

env:
  - DJANGO="Django<1.5"
  - DJANGO="Django<1.6"
  - DJANGO="Django<1.6" LOCALFLAVOR=django-localflavor SQLALCHEMY="SQLAlchemy<0.8"
  - DJANGO="Django<1.7" LOCALFLAVOR=django-localflavor SQLALCHEMY="SQLAlchemy<0.9"

matrix:
  exclude:
    - python: 3.3
      env: DJANGO="Django<1.5"

install:
  - "pip install $DJANGO $LOCALFLAVOR $SQLALCHEMY"
  - "pip install -r tests/test_requirements.txt"

script: "coverage run tests/runtests.py --with-pep8 --force-all"

after_success:
  - pip install coveralls
  - coveralls
