language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - pypy
env:
  global:
    - DATEUTIL=python-dateutil==2.1
    - LOCALFLAVOR=
  matrix:
    - DJANGO=Django==1.3.7
    - DJANGO=Django==1.4.8
    - DJANGO=Django==1.5.4 DATEUTIL=python-dateutil==2.2
    - DJANGO=Django==1.5.4 LOCALFLAVOR=django-localflavor
    - DJANGO=https://github.com/django/django/tarball/stable/1.6.x LOCALFLAVOR=django-localflavor

matrix:
  exclude:
    - python: 3.3
      env: DJANGO=Django==1.3.7
    - python: 3.3
      env: DJANGO=Django==1.4.8

# command to install dependencies
install:
  - "pip install $DJANGO $DATEUTIL $LOCALFLAVOR --use-mirrors"
  - "pip install . --use-mirrors"
  - "pip install -r tests/test_requirements.txt --use-mirrors"

# command to run tests
script: coverage run --source=wtforms tests/runtests.py --with-pep8
after_success:
  - coveralls
